### ISSUE TITLE
Want to contribute !

### ISSUE THREAD

**Issue by AdityaTeltia** [RedHatOfficial/RedHatOfficial.github.io#260]
Hello everyone ! 
I really want to contribute in this but i don't know 
I know HTML , CSS , JAVASCRIPT and C++ .
I am a code newbie so i don't know much but it would be awesome if anyone can mentor me how to do it . 
I have been contributing in some projects in past 2-3 weeks but i have seen this project and i am very keen to contribute and learn new thing !
PS: Maybe it is not the right place to ask , i am sorry if so 
Thankyou

**Comment by castastrophe** [comment]
Hi @AdityaTeltia, thanks for reaching out. Feel free to check out issue queues for ways to contribute. Projects often use the "good first issue" label as a way of noting which issues are easy to jump into without much background. This is not a great project to step into because it's a fairly static listing of Red Hat's open source projects on GitHub and is not supported by a team.
